// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: api/dockerimage/v1/dockerImage.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadDockerImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`       // image tar file path.
	Repo    string `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`       // image repo address.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // image version.
}

func (x *LoadDockerImageRequest) Reset() {
	*x = LoadDockerImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dockerimage_v1_dockerImage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadDockerImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadDockerImageRequest) ProtoMessage() {}

func (x *LoadDockerImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dockerimage_v1_dockerImage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadDockerImageRequest.ProtoReflect.Descriptor instead.
func (*LoadDockerImageRequest) Descriptor() ([]byte, []int) {
	return file_api_dockerimage_v1_dockerImage_proto_rawDescGZIP(), []int{0}
}

func (x *LoadDockerImageRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LoadDockerImageRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *LoadDockerImageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type LoadDockerImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoadDockerImageReply) Reset() {
	*x = LoadDockerImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dockerimage_v1_dockerImage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadDockerImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadDockerImageReply) ProtoMessage() {}

func (x *LoadDockerImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dockerimage_v1_dockerImage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadDockerImageReply.ProtoReflect.Descriptor instead.
func (*LoadDockerImageReply) Descriptor() ([]byte, []int) {
	return file_api_dockerimage_v1_dockerImage_proto_rawDescGZIP(), []int{1}
}

type PushDockerImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo    string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`       // image repo address.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // image version.
}

func (x *PushDockerImageRequest) Reset() {
	*x = PushDockerImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dockerimage_v1_dockerImage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushDockerImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDockerImageRequest) ProtoMessage() {}

func (x *PushDockerImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dockerimage_v1_dockerImage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDockerImageRequest.ProtoReflect.Descriptor instead.
func (*PushDockerImageRequest) Descriptor() ([]byte, []int) {
	return file_api_dockerimage_v1_dockerImage_proto_rawDescGZIP(), []int{2}
}

func (x *PushDockerImageRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *PushDockerImageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PushDockerImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushDockerImageReply) Reset() {
	*x = PushDockerImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dockerimage_v1_dockerImage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushDockerImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDockerImageReply) ProtoMessage() {}

func (x *PushDockerImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dockerimage_v1_dockerImage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDockerImageReply.ProtoReflect.Descriptor instead.
func (*PushDockerImageReply) Descriptor() ([]byte, []int) {
	return file_api_dockerimage_v1_dockerImage_proto_rawDescGZIP(), []int{3}
}

type DeleteRemoteDockerImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo    string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`       // image repo address.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // image version.
}

func (x *DeleteRemoteDockerImageRequest) Reset() {
	*x = DeleteRemoteDockerImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dockerimage_v1_dockerImage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRemoteDockerImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRemoteDockerImageRequest) ProtoMessage() {}

func (x *DeleteRemoteDockerImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dockerimage_v1_dockerImage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRemoteDockerImageRequest.ProtoReflect.Descriptor instead.
func (*DeleteRemoteDockerImageRequest) Descriptor() ([]byte, []int) {
	return file_api_dockerimage_v1_dockerImage_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRemoteDockerImageRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *DeleteRemoteDockerImageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DeleteRemoteDockerImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRemoteDockerImageReply) Reset() {
	*x = DeleteRemoteDockerImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dockerimage_v1_dockerImage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRemoteDockerImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRemoteDockerImageReply) ProtoMessage() {}

func (x *DeleteRemoteDockerImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dockerimage_v1_dockerImage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRemoteDockerImageReply.ProtoReflect.Descriptor instead.
func (*DeleteRemoteDockerImageReply) Descriptor() ([]byte, []int) {
	return file_api_dockerimage_v1_dockerImage_proto_rawDescGZIP(), []int{5}
}

var File_api_dockerimage_v1_dockerImage_proto protoreflect.FileDescriptor

var file_api_dockerimage_v1_dockerImage_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x16, 0x4c, 0x6f, 0x61, 0x64,
	0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x46, 0x0a, 0x16,
	0x50, 0x75, 0x73, 0x68, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x16, 0x0a, 0x14, 0x50, 0x75, 0x73, 0x68, 0x44, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x4e, 0x0a, 0x1e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65,
	0x70, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x1e, 0x0a, 0x1c,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xcb, 0x03, 0x0a,
	0x0b, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x87, 0x01, 0x0a,
	0x0f, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x22, 0x13,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x6c,
	0x6f, 0x61, 0x64, 0x3a, 0x01, 0x2a, 0x12, 0x8a, 0x01, 0x0a, 0x0f, 0x50, 0x75, 0x73, 0x68, 0x44,
	0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x75, 0x73, 0x68, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x3a, 0x01, 0x2a, 0x12, 0xa4, 0x01, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x22, 0x18, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x75, 0x6e,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x3a, 0x01, 0x2a, 0x42, 0x25, 0x5a, 0x23, 0x64, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_dockerimage_v1_dockerImage_proto_rawDescOnce sync.Once
	file_api_dockerimage_v1_dockerImage_proto_rawDescData = file_api_dockerimage_v1_dockerImage_proto_rawDesc
)

func file_api_dockerimage_v1_dockerImage_proto_rawDescGZIP() []byte {
	file_api_dockerimage_v1_dockerImage_proto_rawDescOnce.Do(func() {
		file_api_dockerimage_v1_dockerImage_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_dockerimage_v1_dockerImage_proto_rawDescData)
	})
	return file_api_dockerimage_v1_dockerImage_proto_rawDescData
}

var file_api_dockerimage_v1_dockerImage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_dockerimage_v1_dockerImage_proto_goTypes = []interface{}{
	(*LoadDockerImageRequest)(nil),         // 0: api.dockerimage.v1.LoadDockerImageRequest
	(*LoadDockerImageReply)(nil),           // 1: api.dockerimage.v1.LoadDockerImageReply
	(*PushDockerImageRequest)(nil),         // 2: api.dockerimage.v1.PushDockerImageRequest
	(*PushDockerImageReply)(nil),           // 3: api.dockerimage.v1.PushDockerImageReply
	(*DeleteRemoteDockerImageRequest)(nil), // 4: api.dockerimage.v1.DeleteRemoteDockerImageRequest
	(*DeleteRemoteDockerImageReply)(nil),   // 5: api.dockerimage.v1.DeleteRemoteDockerImageReply
}
var file_api_dockerimage_v1_dockerImage_proto_depIdxs = []int32{
	0, // 0: api.dockerimage.v1.DockerImage.LoadDockerImage:input_type -> api.dockerimage.v1.LoadDockerImageRequest
	2, // 1: api.dockerimage.v1.DockerImage.PushDockerImage:input_type -> api.dockerimage.v1.PushDockerImageRequest
	4, // 2: api.dockerimage.v1.DockerImage.DeleteRemoteDockerImage:input_type -> api.dockerimage.v1.DeleteRemoteDockerImageRequest
	1, // 3: api.dockerimage.v1.DockerImage.LoadDockerImage:output_type -> api.dockerimage.v1.LoadDockerImageReply
	3, // 4: api.dockerimage.v1.DockerImage.PushDockerImage:output_type -> api.dockerimage.v1.PushDockerImageReply
	5, // 5: api.dockerimage.v1.DockerImage.DeleteRemoteDockerImage:output_type -> api.dockerimage.v1.DeleteRemoteDockerImageReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_dockerimage_v1_dockerImage_proto_init() }
func file_api_dockerimage_v1_dockerImage_proto_init() {
	if File_api_dockerimage_v1_dockerImage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_dockerimage_v1_dockerImage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadDockerImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dockerimage_v1_dockerImage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadDockerImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dockerimage_v1_dockerImage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushDockerImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dockerimage_v1_dockerImage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushDockerImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dockerimage_v1_dockerImage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRemoteDockerImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dockerimage_v1_dockerImage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRemoteDockerImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_dockerimage_v1_dockerImage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_dockerimage_v1_dockerImage_proto_goTypes,
		DependencyIndexes: file_api_dockerimage_v1_dockerImage_proto_depIdxs,
		MessageInfos:      file_api_dockerimage_v1_dockerImage_proto_msgTypes,
	}.Build()
	File_api_dockerimage_v1_dockerImage_proto = out.File
	file_api_dockerimage_v1_dockerImage_proto_rawDesc = nil
	file_api_dockerimage_v1_dockerImage_proto_goTypes = nil
	file_api_dockerimage_v1_dockerImage_proto_depIdxs = nil
}
